# Generated by Django 4.2.2 on 2023-07-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matricula',
            new_name='Aluno',
        ),
    ]
