# Generated by Django 4.2.2 on 2023-11-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_rename_matricula_aluno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
