# Generated by Django 4.2.2 on 2023-11-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_quarto_hospedagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.hospedagem')),
            ],
        ),
    ]
